### ISSUE TITLE
add basic commands for contribution in contributing.md file

### ISSUE THREAD

**Issue by Intellimixiopce** [Intellimixiopce/intellimixio#10]
add basic git command for contribution in contributing.md files

**Comment by GyanPrakashRaj** [comment]
> add basic git command for contribution in contributing.md files

Kindly assign this issue to me.

**Comment by AaryanSingh0017** [comment]
Plz assign this to me!

**Comment by Intellimixiopce** [comment]
> > add basic git command for contribution in contributing.md files
> 
> Kindly assign this issue to me.



> > add basic git command for contribution in contributing.md files
> 
> Kindly assign this issue to me.

I have assigned this to you go and work ✔

**Comment by Intellimixiopce** [comment]
i have assigned this issue to you go and work ✔ @GyanPrakashRaj

**Comment by Intellimixiopce** [comment]
Please go to the issue tab & I have added basic issues. go to that, I will assign you and contribute 😍 @AaryanSingh0017
